---
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/debian/gpg
  - name: Check that HTTPS transport is available to APT
    apt: name="apt-transport-https" state=installed update_cache=yes
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
  - name: Install list of packages
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python-pip
  - name: install docker-py
    pip: name=docker-py
  - name: Create folder for conf file
    file:
     path: /data/balance
     state: directory
  - name: Push nginx conf file
    copy: src=nginx.conf dest=/data/balance/nginx.conf
  - name: Check container with same name
    shell: if [ $(docker ps --filter "name=balancing" | wc -l) -gt 1 ]; then docker kill balancing && docker rm balancing; fi
  - name: Start docker container
    command: docker run --name balancing -v /data/balance/nginx.conf:/etc/nginx/nginx.conf  -d -p 1234:1234/udp nginx 
