---
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/debian/gpg
  - name: Check that HTTPS transport is available to APT
    apt: name="apt-transport-https" state=installed update_cache=yes
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
  - name: Install list of packages
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python-pip
  - name: install docker-py
    pip: name=docker-py
  - name: Create folder for Dockerfile and conf file
    file:
     path: /tmp/balance
     state: directory
  - name: Push Dockerfile
    template: src=Dockerfile dest=/tmp/balance/Dockerfile
  - name: Push nginx conf file
    template: src=nginx.conf dest=/tmp/balance/nginx.conf
  - name: Push service file
    template: src=balance.service dest=/etc/systemd/system/balance.service
  - name: Pull nginx container
    command: docker pull nginx
  - name: Change directory and create container balance
    command: chdir=/tmp/balance docker build -t balance ./
  - name: Check container with same name
    shell: if [ $(docker ps --filter "name=balancing" | wc -l) -gt 1 ]; then docker kill balancing && docker rm balancing; fi
  - name: Start docker container
    command: docker run --name balancing -d -p 1234:1234/udp balance
  - name: Reload systemd
    command: systemctl daemon-reload
  - name: Enable autostart
    command: systemctl enable balance
    notify:
     - Restart nginx balancing container
