---
  - name: Install list of packages
    apt:
      name: monit
      state: present
  - name: Push monit GLOBAL conf file
    copy: src=monitrc dest=/etc/monit/monitrc
  - name: Push monit conf file for nginx
    copy: src=nginx dest=/etc/monit/conf.d/nginx
  - name: Reload service monit, in all cases
    service:
      name: monit
      state: reloaded
#  - name: install docker-py
#    pip: name=docker-py
#  - name: Create folder for conf file
#    file:
#     path: /data/balance
#     state: directory
#  - name: Push nginx conf file
#    copy: src=nginx.conf dest=/data/balance/nginx.conf
#  - name: Check container with same name
#    shell: if [ $(docker ps --filter "name=balancing" | wc -l) -gt 1 ]; then docker kill balancing && docker rm balancing; fi
#  - name: Start docker container
#    command: docker run --name balancing -v /data/balance/nginx.conf:/etc/nginx/nginx.conf  -d -p 1234:1234/udp nginx 
