---
  - name: Create folder for conf file
    file:
     path: /data/keepalived
     state: directory
  - name: Push config files
    copy:
      src: "{{ item }}"
      dest: "/data/keepalived/{{ item }}"
    with_items:
      - env.yaml
      - keepalived.conf
  - name: Check container with same name
    shell: if [ $(docker ps --filter "name=keepalived" | wc -l) -gt 1 ]; then docker kill keepalived && docker rm keepalived; fi
  - name: Enable ip_vs
    command: modprobe ip_vs
  - name: Enable ip_vs on autostart
    command: echo ip_vs > /etc/modules
  - name: Start container
    command: >
     docker run --name keepalived -v /data/keepalived.conf:/container/service/keepalived/assets/keepalived.conf 
     -v /data/env.yaml:/container/environment/01-custom/env.yaml --cap-add=NET_ADMIN --net=host -d 
     osixia/keepalived --copy-service
